### PR TITLE
clearstat downloader

### PR DESCRIPTION
**Pull request by aclyonsita**
Test renaming columns

### CODE REVIEW

**Comment by aclyonsita** [comment]
Updated pull request.  Now postgres downloader updates.

**Comment by ian-r-rose** [comment]
@hunterowens Add segment id to the cleanstat table

**Comment by ian-r-rose** [comment]
@ian-r-rose Remove empty cells and commented-out-code.

**Comment by ian-r-rose** [comment]
Move to a script once this is done.

**Pull request merged**
